# Generated by Django 5.0.3 on 2024-03-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_joined_date_member_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
